---
title: "中国青少年心理健康热点话题和研究趋势：基于网络爬虫和数据可视化的讨论"
author: "罗焱丰 2000013134"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: yes
    number_sections: yes
  html_document:
    toc: yes
    df_print: paged
  pdf_document: default
  word_document: default
---

# 设计方案

## 背景介绍

青少年心理健康问题受到社会和研究者的广泛关注。本课题期望通过网络爬虫，以微博为网络社交媒体的代表，收集大众对于青少年心理健康的讨论。同时，由于知网是目前中文研究最全面的文献检索平台之一，本课题还希望通过网络爬虫，爬取相关研究信息，将其与微博上大众关于青少年心理健康话题的讨论进行比较和分析，总结国内关于此话题的研究趋势和动向。

## 数据信息汇总

以"青少年心理健康"为关键词在微博平台进行检索，分别以"青少年 心理健康""青少年 抑郁""青少年 焦虑""学校 心理健康""学校 抑郁""学校 焦虑"作为关键词在知网进行检索，并分别使用爬虫抓取微博文案与文献标题，摘要，发表年份被引量和被下载量等信息。总共爬取20+小时，爬取总数据量23000+条。最终，在去掉重复数据后，共有800+微博话题文本和15000+项研究纳入本课题的讨论之中。

# 可视化结果与讨论

## 社交媒体讨论与研究热点话题对比

微博和知网关于青少年心理健康讨论的词云图如下所示。如图所示，大众对于青少年心理健康话题的讨论和科学研究中存在一些共同热点话题，例如讨论家庭和学校在其中的角色、体育运动对于青少年心理健康的影响与心理咨询和干预对青少年心理健康相关症状的作用。但除此之外，大众讨论更加关注社会对青少年心理健康发展的影响，比如社会公益活动等；而相关研究则更加关注政策对青少年心理健康的影响与心理干预的效果检验和起效机制的探索。

## 国内青少年心理健康研究趋势

如下图所示，自上个世纪90年代以来，我国对青少年心理健康的研究兴趣整体呈现上升的趋势，每年发表的中文文献数量也呈现上升的趋势。同时，下图还反映出，2004年以前，青少年心理健康中文文献的被引量和下载量均表现出较高的水平，然而2004年以后这两个指标却整体维持在较低水平，这与逐渐上升的年发表量之间存在一定的矛盾。分析其原因，可能是进入二十一世纪以来，我国与世界交融程度逐渐加深，而我国与欧美国家之间的科研实力还存在不容小觑的差距，同时中文研究和期刊自身存在着良莠不齐等诸多问题，因此尽管青少年心理健康相关研究的年发表量呈现上升的趋势，但该领域内每年的被引量和下载量均维持在较低水平。未来需要提高青少年心理健康相关中文研究的研究质量，严格把控科学刊物的遴选机制，以缩小该话题下中文研究和国外研究之间质上的差距，使更多人选择下载或引用中文研究，以推动该领域内中文研究的发展。

# 课题总结

## 局限性与未来展望

1.  微博数据较少，只有几百条数据，与研究的信息量难以匹配（原定本来还想爬知乎的数据，但奈何爬取过程中遭到了反爬机制的阻拦，由于大作业时限问题最终只能放弃）；

2.  爬取了文章摘要，但未对其进行挖掘。后续可以进行关键词共现分析，深度挖掘并讨论目前对于青少年心理健康研究中各热点话题之间的关系；

3.  本来想看看英文研究，再与中文研究之间进行对比，奈何Google Scholar的反爬机制真的非常完善，加上时间限制的问题，所以最终放弃了

## 课题亮点

1.  爬取时间长（20+小时），数据量较大（23000+条数据）；

2.  数据类型丰富，包含了社交媒体和科研检索平台对青少年心理健康的讨论；

3.  话题新颖有趣，结合比较大众和研究人员对"青少年心理健康"话题的讨论，对该主题进行了较丰富地概览和介绍；

4.  对国内青少年心理健康话题下的研究趋势基于可视化进行了分析和讨论，并对未来发展进行了展望；

5.  为保留可视化中交互的功能，本课题最终报告使用HTML形式呈现。

# 备注

-   词云图需要刷新网页才能看到

-   本报告及相关材料均已上传至个人GitHub网页，可直接通过\"https://threefire7.github.io/大作业展示报告.html\"进行浏览，报告中所涉及的三个可视化网页文件链接按照呈现的先后顺序分别为：

    \"https://threefire7.github.io/微博青少年心理健康词云图.html"

    \"https://threefire7.github.io/wordcloud_cnki_keywords.html"

    \"https://threefire7.github.io/文献发表频次统计条形图.html"
